import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        "inverse-primary": "#b22e00",
        "primary-fixed": "#ffad96",
        "on-secondary-container": "#00b4c9",
        "secondary-container": "#002a30",
        "surface-container-low": "#171210",
        "on-surface": "#f0e3dd",
        "on-secondary": "#004750",
        "on-error-container": "#ff9993",
        "outline-variant": "#4f4642",
        "tertiary-container": "#fdd400",
        "surface-container-high": "#241e1b",
        "tertiary-fixed-dim": "#edc600",
        "surface": "#110d0c",
        "error": "#ff716c",
        "on-surface-variant": "#b4a9a3",
        "on-secondary-fixed": "#00464f",
        "inverse-on-surface": "#5a5451",
        "tertiary-dim": "#edc600",
        "inverse-surface": "#fff8f5",
        "error-container": "#8a1a1e",
        "on-primary": "#430c00",
        "surface-container-highest": "#2b2421",
        "surface-variant": "#2b2421",
        "on-primary-fixed-variant": "#842000",
        "secondary-dim": "#00cbe2",
        "on-error": "#490006",
        "surface-bright": "#322a26",
        "secondary": "#00daf3",
        "primary": {
          DEFAULT: "#ff734b",
          foreground: "#430c00",
        },
        "surface-container-lowest": "#000000",
        "on-primary-container": "#250400",
        "secondary-fixed": "#9cf0ff",
        "on-secondary-fixed-variant": "#006571",
        "on-tertiary-fixed": "#433700",
        "on-tertiary-fixed-variant": "#645300",
        "tertiary": "#ffe483",
        "surface-tint": "#ff734b",
        "on-tertiary-container": "#594a00",
        "on-tertiary": "#635200",
        "background": "#110d0c",
        "secondary-fixed-dim": "#49e7ff",
        "on-background": "#f0e3dd",
        "outline": "#7d736f",
        "primary-dim": "#ff734b",
        "tertiary-fixed": "#fdd400",
        "primary-container": "#fc5929",
        "error-dim": "#c94947",
        "surface-container": "#1e1816",
        "primary-fixed-dim": "#ff987b",
        "on-primary-fixed": "#501000",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "slide-in": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        confetti: {
          "0%": { transform: "translateY(0) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(100vh) rotate(720deg)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        confetti: "confetti 3s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
